### ISSUE TITLE
updated theme

### ISSUE THREAD

**Issue by mauricecruz** [s-a/iron-node-zerodarkmatrix-theme#1]
Hey there!

Noticed the theme broke with the latest version of your app. I updated my repo with the latest. Tried to fork and update but was having some difficulty. 

In any case, if you update this repo, the theme should be fixed in your app.

Awesome work on iron-node! Really appreciate the time you put into it!

**Comment by s-a** [comment]
Hi,
glad you like it. I am a fan of your theme.
Your repo is a submodule here. You can update it local with `git submodule update --recursive` to test your changes.  
I think it should work if we bump the version number of this repo and publish to npm to deploy a new version. I can do it this weekend.

**Comment by s-a** [comment]
Ok i see the submodule is linked to a special commit of your repo. We need to update the module and commit the changes to this repo.

**Comment by s-a** [comment]
Thank you. Done with https://github.com/s-a/iron-node-zerodarkmatrix-theme/releases/tag/v1.0.6
